#!/bin/bash
IAXstatus=$(asterisk -rx "IAX2 show peers" | awk 'END{print $4}' | cut -d "[" -f2)
if [ $IAXstatus == 0 ]
then
sendmail -t raghu@example.com << EOF
	From: alerts@example.com
	Subject: IAX Peers status is zero
	Hi Team,
	No Peers in Online
	EOF
else
echo "Few are Online"
fi
