#!/bin/bash
# here we collect the status of iax peers. in the same way we can get the status of sip.
IAXstatus=$(asterisk -rx "IAX2 show peers" | awk 'END{print $4}' | cut -d "[" -f2)
if [ $IAXstatus == 0 ]
then
# sendmail will use to send an email, -F will display from email name.
sendmail -F Alerts -f alerts@example.com -t raghu@example.com << EOF
Subject: IAX Peers status is zero
Hi Team,
No Peers Online
EOF
else
echo "Few are Online"
fi
