#!/usr/bin/python2.7
# In this script we are displaying hostname, cpu's count, load average of cpu

# Importing socket library
import socket

# Importing subprocess to execute linux commands
import subprocess

# importing os library to call linux commands
import os

# importing multiprocessing to get number of cpu's
import multiprocessing

# Printing hostname
hostName = socket.gethostname()
print "Host Name is:", hostName

# Printing number of CPU's using the module multiprocessing
print "Number of CPU's:",multiprocessing.cpu_count()

# Calling linux command directly using "os.popen"
topc = os.popen('top -b -n 1')

# here it will read the output of cpuInf and add to variable
cpuInf = topc.read()

# Printing first line from the output by using split("\n")[0], zero represents first line
firstLi = cpuInf.split('\n')[0]

# here the dificulty i faced, considering space as a character when comma is there after string(i.e: hello, )
print "Load Average of 5 Minutes:",firstLi.split(' ')[12], "10 Minutes:",firstLi.split(' ')[13], "15 Minutes:",firstLi.split(' ')[14]
